mysql_data:
  volumes:
    - /var/lib/mysql
  image: mysql
  command: /bin/true
mysql:
  image: mysql
  volumes_from:
    - mysql_data
  environment:
    - MYSQL_ROOT_PASSWORD=CHANGEIT
    - MYSQL_DATABASE=warnings
    - MYSQL_USER=warning_user
    - MYSQL_PASSWORD=CHANGEIT
warning_server:
  build: .
  ports:
    - "80:8080"
  links:
    - mysql
  environment:
    - MYSQL_HOST=mysql
    - MYSQL_DATABASE=warnings
    - MYSQL_USER=warning_user
    - MYSQL_PASSWORD=CHANGEIT
